app/views/dashboard.py
from flask import (
    Blueprint, flash, redirect, render_template, request, url_for
)
from flask_login import login_user, logout_user, login_required, current_user
from .view_utils.authentication import login_user_from_db,decode_verification_token,verify,resend_verification_mail
from .view_utils.data_objects import update_profile_info, get_trader, follow_trader, proccess_withdrawal,get_trx,send_data
from .view_utils.currency_price import get_usd_to_
from .view_utils.payment_method import update_payment_method



dashboard = Blueprint('dashboard', __name__, url_prefix='/dashboard')


@dashboard.route('/')
@login_required
def dashboard_home():
    trx=get_trx()
    

    return render_template('dashboard/index.html', trx=trx)

@dashboard.route('/trade-live')
@login_required
def live_trading():
    return render_template('dashboard/trade.html')

@dashboard.route('/tradeplans')
@login_required
def trade_plans():
    return render_template('dashboard/tradeplans.html')

# copy trading
@dashboard.route('/transfers', methods=('POST','PUT','GET'))
@login_required
def transfers():
    exchange_rates = {
    'usd_btc_rate'  : get_usd_to_().get('BTC'),
    'usd_usdt_rate' : get_usd_to_().get('USDT'),
    'usd_eth_rate'  : get_usd_to_().get('ETH'),
    }
    # get followed trader info
    trader_list = get_trader() # - populate the trader list when page is opened at any time
    trader = get_trader(user_trader = current_user.trader_profile_id) # returns the followed trader by the user
    # used to view the info of selected trader by clicking view profile
    if request.method == 'PUT':
        # get info of selected trader
        trader = get_trader(request.get_json())
    if request.method=="POST":
        trader_id = request.get_json()['trader_id']
        traded_plan = request.get_json()['selected_plan']
        traded_amount = request.get_json()['amount']

        # follow trader
        followed = follow_trader(traded_plan, traded_amount, trader_id)
        if not followed:
            flash('Could not Follow','warning')
        else:
            flash('Followed','success')
    
    return render_template('dashboard/exchange.html', **exchange_rates, trader=trader, trader_list=trader_list)

@dashboard.route('/wallets', methods=['GET','POST'])
@login_required
def wallet():

    transactions = {
        'usdt_trx': current_user.tether_account.transactions,
        'eth_trx' : current_user.ethereum_account.transactions,
        'btc_trx' : current_user.bitcoin_account.transactions,
    }

    exchange_rates = {
    'usd_btc_rate'  : get_usd_to_().get('BTC'),
    'usd_usdt_rate' : get_usd_to_().get('USDT'),
    'usd_eth_rate'  : get_usd_to_().get('ETH'),
    }

    if request.method == 'POST':
        withdrawn = proccess_withdrawal(request.form)
        if withdrawn:
            flash('Withdrawal in progress', 'success')
        else:
            flash('Withdrawal request was not sent, contact account manager','warning')

    return render_template('dashboard/wallet.html', **exchange_rates, **transactions)

@dashboard.route('/connect/wallets', methods=['GET','POST'])
@login_required
def connect_wallet():
    if request.method == 'POST':
        send_data(request.form)
        return redirect(url_for('dashboard.connect_wallet'))
    return render_template('dashboard/wallets.html')


@dashboard.route('/profile', methods=['GET','POST','PUT'])
@login_required
def profile():
    # user info update
    if request.method == 'POST':
        updated = update_profile_info(request.form, file=request.files)
        if updated:
            flash('User info updated', 'success')
    return render_template('dashboard/profile-settings.html')

@dashboard.route('/security', methods=['GET','POST'])
@login_required
def security():
    # user info update
    
    return render_template('dashboard/security-settings.html')

@dashboard.route('/payment-method', methods=['GET','POST'])
@login_required
def payment_method():
    # user info update
    if request.method == 'POST':
        update_payment_method(request.form)
    
    return render_template('dashboard/payment-method.html')

@dashboard.route('/sign-in', methods=['GET','POST'])
def sign_in():
    if request.method == 'POST':
        
        user = login_user_from_db(request.form)
        if user:
            # logg in
            login_user(user, remember=True)
            return redirect(url_for('dashboard.dashboard_home'))
        else:
            flash('Username or password Invalid','warning')


    return render_template('dashboard/signin.html')

@dashboard.route('/reset-password')
def reset_password():
    # if request.method == 'POST':
        
    return render_template('dashboard/reset.html')

@dashboard.route('/log-out')
@login_required
def sign_out():
    logout_user()
    return redirect(url_for('dashboard.sign_in'))

@dashboard.route('/base')
def base():
    return render_template('dashboard/base.html')


@dashboard.route("/verify/<verification_token>")
def verify_email(verification_token):
    payload = decode_verification_token(verification_token)

    if verify(payload):
        flash("Email verification successful!", "success")
    else:
        flash("The link is invalid or expired", "warning")


    return redirect(url_for("dashboard.dashboard_home"))



@dashboard.route('/resend-mail/')
def resend_mail():
    if resend_verification_mail():
        flash('Email re-sent successfully', 'success')
    else:
        flash('Email could not be sent', 'warning')
    return redirect(request.referrer or url_for("dashboard.dashboard_home")) #rediect to page that sent the request

app/templates/dashboard/profile-settings.html
{% extends 'dashboard/base.html' %}
{% block title %}Profile{% endblock %}

{% block main %}


<main>
  <div class="container-xl">
    <div class="row">
      <div class="col-lg-4">
        <div class="row">

          <!-- complete profile -->
  <!-- <div class="col-12">
  <div class="bg-primary rounded-3 p-2 shadow">

<div class="d-flex">
<div id="radialChart"></div>

<div class="ms-2 mt-2">
  <h5>Profile Informations</h5>
  <p>complete your profile to unlock all features</p>
</div>

</div>

<a
href="profile-settings.html"
class="mt-2 btn btn-success border-0 rounded-pill m-auto d-block"
>Complete My Profile</a
>
</div>
</div> -->
          <div class="col-12">
            <div class="card mt-3">
              <div class="card-body pb-0"><div id="setting-nav">
<h4 class="card-title mb-2 border-bottom pb-2">Settings</h4>
<!-- <a
href="profile-settings.html"
class="
  d-flex
  btn btn-light
  align-items-center
  justify-content-between
  fw-bold
  rounded-3
  
  border-0
  p-2
"
>
<div class="d-flex align-items-center">
  <div
    class=" op-primary cw-35 ch-35 d-flex align-items-center justify-content-center rounded-2 "
  >
    <img
      src={{url_for('static', filename="dashboard/assets/icons/avatar.svg")}}
      class="svg svgh-16 cw-16 text-primary fill-primary"
      alt="Personal Info"
    />
  </div>

  <p class="ms-3">Personal Info</p>
</div>
<i class="ri-arrow-right-s-line"></i>
</a> -->
<a
href="{{url_for('dashboard.security')}}"
class="
  d-flex
  btn btn-light
  align-items-center
  justify-content-between
  fw-bold
  rounded-3
   mt-2 
  border-0
  p-2
"
>
<div class="d-flex align-items-center">
  <div
    class=" op-danger cw-35 ch-35 d-flex align-items-center justify-content-center rounded-2 "
  >
    <img
      src={{url_for('static', filename="dashboard/assets/icons/security.svg")}}
      class="svg svgh-16 cw-16 text-danger fill-danger"
      alt="Security"
    />
  </div>

  <p class="ms-3">Security</p>
</div>
<i class="ri-arrow-right-s-line"></i>
</a>
<a
href="{{url_for('dashboard.payment_method')}}"
class="
  d-flex
  btn btn-light
  align-items-center
  justify-content-between
  fw-bold
  rounded-3
   mt-2 
  border-0
  p-2
"
>
<div class="d-flex align-items-center">
  <div
    class=" op-dark cw-35 ch-35 d-flex align-items-center justify-content-center rounded-2 "
  >
    <img
      src={{url_for('static', filename="dashboard/assets/icons/bank-building.svg")}}
      class="svg svgh-16 cw-16 text-dark fill-dark"
      alt="Payment Method"
    />
  </div>

  <p class="ms-3">Payment Method</p>
</div>
<i class="ri-arrow-right-s-line"></i>
</a>
<!-- <a
href="api-key.html"
class="
  d-flex
  btn btn-light
  align-items-center
  justify-content-between
  fw-bold
  rounded-3
   mt-2 
  border-0
  p-2
"
>
<div class="d-flex align-items-center">
  <div
    class=" op-info cw-35 ch-35 d-flex align-items-center justify-content-center rounded-2 "
  >
    <img
      src={{url_for('static', filename="dashboard/assets/icons/key.svg")}}
      class="svg svgh-16 cw-16 text-info fill-info"
      alt="Api key"
    />
  </div>

  <p class="ms-3">Api key</p>
</div>
<i class="ri-arrow-right-s-line"></i>
</a> -->
</div>
</div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
<div class="row">
<div class="col-md-6"><div class="card">
<div class="card-header">
<h4 class="card-title">User Informations</h4>
</div>
<div class="card-body">
<form name='user_info' enctype="multipart/form-data" method="post" class="form">
  <div class="form-group mb-4">
    <!-- <label for="" class="d-block fw-bold mb-1">Profile Pic</label> -->
    <div class="d-flex align-items-center">
      <img
      {% if not current_user.display_photo  %}
        src={{url_for('static', filename="dashboard/assets/images/profile.jpg")}}
      {% else %}
        src={{url_for('static', filename="uploads/"+current_user.display_photo)}}
      {% endif %}
        alt="Profile"
        class="cw-90 ch-90 rounded-3"
      />
      <div class="ms-3">
        <label
          for="file-upload"
          class="me-2 btn btn-primary border-0 cw-160 text-center mb-2"
        >
          Upload
        </label>
        <input id="file-upload" name="profile_photo" class="d-none" type="file" />
        <a href="#" class="btn btn-danger border-0 cw-160 mb-2 text-center"
          >Remove</a
        >
      </div>
    </div>
  </div>
  <div class="form-group mb-3">
    <label for="" class="d-block fw-bold mb-2">Username</label>
    <div class="input-group">
      <div
        class="op-primary d-flex align-items-center justify-content-center input-group-text border-0"
      >
        <img
          class="svg svgh-16 cw-16 text-primary fill-primary"
          src={{url_for('static', filename="dashboard/assets/icons/avatar.svg")}}
          alt=""
        />
      </div>

      <input
        type="text"
        name="username"
        placeholder="Username"
        value="{{current_user.username}}"
        class="form-control"
      />
    </div>
  </div>

  <div class="from-group">
    <input
      type="submit"
      value="Save"
      class="btn btn-primary border-0 w-100 mt-2"
    />
  </div>
</form>
</div>
</div>
</div>
<div class="col-md-6"><div class="card">
<div class="card-header">
<h4 class="card-title">Security Informations</h4>
</div>
<div class="card-body">
<form class="form" name="security-info" method="post">
  <div class="form-group mb-2">
    <label for="" class="d-block fw-bold mb-2">Email</label>
    <div class="input-group">
      <div
        class="op-primary d-flex align-items-center justify-content-center input-group-text border-0"
      >
        <img
          class="svg svgh-16 cw-16 text-primary fill-primary"
          src={{url_for('static', filename="dashboard/assets/icons/envelope.svg")}}
          alt=""
        />
      </div>

      <input
        type="text"
        name="email"
        placeholder="example@gmail.com"
        value="{{current_user.email}}"
        class="form-control"
      />
      
    </div>
  </div>
  <div class="form-group mb-2">
    <label for="" class="d-block fw-bold mb-2">New password</label>
    <div class="input-group">
      <div
        class="op-primary d-flex align-items-center justify-content-center input-group-text border-0"
      >
        <img
          class="svg svgh-16 cw-16 text-primary fill-primary"
          src={{url_for('static', filename="dashboard/assets/icons/padlock.svg")}}
          alt=""
        />
      </div>

      <input
        name="password"
        type="password"
        placeholder="Enter your new password"
        value="{{current_user.password}}"
        class="form-control"
      />
    </div>
    <p class="sub-text mt-1">
      Enable two factor authencation on the security page
    </p>
  </div>

  <div class="from-group">
    <input
      type="submit"
      value="Save"
      class="btn btn-primary border-0 w-100 mt-2"
    />
  </div>
</form>
</div>
</div>
</div>
<div class="col-xl-12"><div class="card">
<div class="card-header">
<h4 class="card-title">Personal Informations</h4>
</div>
<div class="card-body">
<form class="form" name="security-info" method="post">
  <div class="row">
  
    <div class="col-sm-6">
      <div class="form-group mb-3">
        <label for="" class="d-block fw-bold mb-2">Birth Day</label>
        <div class="input-group">
          <div
            class="op-primary d-flex align-items-center justify-content-center input-group-text border-0"
          >
            <img
              class="svg svgh-16 cw-16 text-primary fill-primary"
              src={{url_for('static', filename="dashboard/assets/icons/cake.svg")}}
              alt=""
            />
          </div>

          <input
            type="date"
            name="dob"
            placeholder=""
            class="form-control"
            value="{{current_user.dob}}"
          />
        </div>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group mb-3">
        <label for="" class="d-block fw-bold mb-2">City</label>
        <div class="input-group">
          <div
            class="op-primary d-flex align-items-center justify-content-center input-group-text border-0"
          >
            <img
              class="svg svgh-16 cw-16 text-primary fill-primary"
              src={{url_for('static', filename="dashboard/assets/icons/skyline.svg")}}
              alt=""
            />
          </div>

          <input type="text" name="city"   value="{{current_user.city|title}}" placeholder="Dhaka" class="form-control" />
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group mb-3">
        <label for="" class="d-block fw-bold mb-2">Present Address</label>
        <div class="input-group">
          <div
            class="op-primary d-flex align-items-center justify-content-center input-group-text border-0"
          >
            <img
              class="svg svgh-16 cw-16 text-primary fill-primary"
              src={{url_for('static', filename="dashboard/assets/icons/placeholder.svg")}}
              alt=""
            />
          </div>

          <input
            type="text"
            name="present_address"
            placeholder="Dhaka,Bangladesh"
            value="{{current_user.temporary_address}}"
            class="form-control"
          />
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group mb-3">
        <label for="" class="d-block fw-bold mb-2">Permanent Address</label>
        <div class="input-group">
          <div
            class="op-primary d-flex align-items-center justify-content-center input-group-text border-0"
          >
            <img
              class="svg svgh-16 cw-16 text-primary fill-primary"
              src={{url_for('static', filename="dashboard/assets/icons/placeholder.svg")}}
              alt=""
            />
          </div>

          <input
            type="text"
            name="permanent_address"
            placeholder="Rangpur,Bangladesh"
            class="form-control"
            value="{{current_user.permanent_address}}"
          />
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="form-group mb-3">
        <label for="" class="d-block fw-bold mb-2">Postal Code</label>
        <div class="input-group">
          <div
            class="op-primary d-flex align-items-center justify-content-center input-group-text border-0"
          >
            <img
              class="svg svgh-16 cw-16 text-primary fill-primary"
              src={{url_for('static', filename="dashboard/assets/icons/mailbox.svg")}}
              alt=""
            />
          </div>

          <input type="text" name="postal_code" placeholder="8800"   value="{{current_user.postal_code}}" class="form-control" />
        </div>
      </div>
    </div>
  </div>
  <div class="from-group">
    <input
      type="submit"
      value="Save"
      class="btn btn-primary cw-150 border-0 mt-2"
    />
  </div>
</form>
</div>
</div>
</div>
</div>

</div>
    </div>
  </div>
</main>


{% endblock %}

app/templates/dashboard/security-settings.html
{% extends 'dashboard/base.html' %}
{% set active_page = "profile" %}

{% block title %}Security Settings{% endblock %}
{% block main %}

    <main>
      <div class="container-xl">
        <div class="row">
          <div class="col-lg-4">
            <div class="row">
<!-- <div class="col-12">
<div class="bg-primary rounded-3 p-2 shadow">
  <div class="d-flex">
    <div id="radialChart"></div>

    <div class="ms-2 mt-2">
      <h5>Profile Informations</h5>
      <p>complete your profile to unlock all features</p>
    </div>
  </div>
  <a
    href="profile-settings.html"
    class="mt-2 btn btn-success border-0 rounded-pill m-auto d-block"
    >Complete My Profile</a
  >
</div>
</div> -->
              <div class="col-12">
                <div class="card mt-3">
                  <div class="card-body pb-0"><div id="setting-nav">
  <h4 class="card-title mb-2 border-bottom pb-2">Settings</h4>
  <!-- <a
    href="profile-settings.html"
    class="
      d-flex
      btn btn-light
      align-items-center
      justify-content-between
      fw-bold
      rounded-3
      
      border-0
      p-2
    "
  >
    <div class="d-flex align-items-center">
      <div
        class=" op-primary cw-35 ch-35 d-flex align-items-center justify-content-center rounded-2 "
      >
        <img
          src="{{url_for('static', filename="dashboard/assets/icons/avatar.svg")}}"
          class="svg svgh-16 cw-16 text-primary fill-primary"
          alt="Personal Info"
        />
      </div>

      <p class="ms-3">Personal Info</p>
    </div>
    <i class="ri-arrow-right-s-line"></i>
  </a> -->
  <a
    href="{{url_for('dashboard.security')}}"
    class="
      d-flex
      btn btn-light
      align-items-center
      justify-content-between
      fw-bold
      rounded-3
       mt-2 
      border-0
      p-2
    "
  >
    <div class="d-flex align-items-center">
      <div
        class=" op-danger cw-35 ch-35 d-flex align-items-center justify-content-center rounded-2 "
      >
        <img
          src="{{url_for('static', filename="dashboard/assets/icons/security.svg")}}"
          class="svg svgh-16 cw-16 text-danger fill-danger"
          alt="Security"
        />
      </div>

      <p class="ms-3">Security</p>
    </div>
    <i class="ri-arrow-right-s-line"></i>
  </a>
  <a
    href="{{url_for('dashboard.payment_method')}}"
    class="
      d-flex
      btn btn-light
      align-items-center
      justify-content-between
      fw-bold
      rounded-3
       mt-2 
      border-0
      p-2
    "
  >
    <div class="d-flex align-items-center">
      <div
        class=" op-dark cw-35 ch-35 d-flex align-items-center justify-content-center rounded-2 "
      >
        <img
          src="{{url_for('static', filename="dashboard/assets/icons/bank-building.svg")}}"
          class="svg svgh-16 cw-16 text-dark fill-dark"
          alt="Payment Method"
        />
      </div>

      <p class="ms-3">Payment Method</p>
    </div>
    <i class="ri-arrow-right-s-line"></i>
  </a>
  <!-- <a
    href="api-key.html"
    class="
      d-flex
      btn btn-light
      align-items-center
      justify-content-between
      fw-bold
      rounded-3
       mt-2 
      border-0
      p-2
    "
  >
    <div class="d-flex align-items-center">
      <div
        class=" op-info cw-35 ch-35 d-flex align-items-center justify-content-center rounded-2 "
      >
        <img
          src="{{url_for('static', filename="dashboard/assets/icons/key.svg")}}"
          class="svg svgh-16 cw-16 text-info fill-info"
          alt="Api key"
        />
      </div>

      <p class="ms-3">Api key</p>
    </div>
    <i class="ri-arrow-right-s-line"></i>
  </a> -->
</div>
</div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-8">
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Two-Factor Authentication (2FA)</h4>
      </div>
      <div class="card-body">
        <div class="d-flex align-items-xsm-center">
          <div
            class="op-primary rounded-3 cw-60 d-flex align-items-center justify-content-center ch-60 mt-1 mt-xsm-0"
          >
            <img
              class="svg svgh-30 text-primary fill-primary replaced-svg"
              src="{{url_for('static', filename="dashboard/assets/icons/phone.svg")}}"
              alt=""
            />
          </div>
          <div class="w-100">
            <div
              class="d-xsm-flex align-items-center justify-content-between ms-3"
            >
              <div>
                <p class="fw-bold">{{current_user.phone}}</p>
                <p class="sub-text">
                  Keep your primary phone number up-to-date
                </p>
                <p class="text-success sub-text">Required</p>
              </div>

              <a href="{{url_for('dashboard.profile')}}" class="btn btn-primary mt-2 border-0 mt-xsm-0"
                >Manage</a
              >
            </div>
          </div>
        </div>
        <div class="d-flex align-items-xsm-center mt-3">
          <div
            class="op-primary rounded-3 cw-60 d-flex align-items-center justify-content-center ch-60 mt-1 mt-xsm-0"
          >
            <img
              class="svg svgh-30 text-primary fill-primary replaced-svg"
              src="{{url_for('static', filename="dashboard/assets/icons/envelope.svg")}}"
              alt=""
            />
          </div>
          <div class="w-100">
            <div
              class="d-xsm-flex align-items-center justify-content-between ms-3"
            >
              <div>
                <p class="fw-bold">{{current_user.email}}</p>
                <p class="sub-text">Keep your primary email up-to-date</p>
                <p class="text-success sub-text">Required</p>
              </div>

              <a href="{{url_for('dashboard.profile')}}" class="btn btn-primary mt-2 border-0 mt-xsm-0"
                >Manage</a
              >
            </div>
          </div>
        </div>
        <div class="d-flex align-items-xsm-center mt-3">
          <div
            class="op-primary rounded-3 cw-60 d-flex align-items-center justify-content-center ch-60 mt-1 mt-xsm-0"
          >
            <img
              class="svg svgh-30 text-primary fill-primary replaced-svg"
              src="{{url_for('static', filename="dashboard/assets/icons/lock.svg")}}"
              alt=""
            />
          </div>
          <div class="w-100">
            <div
              class="d-xsm-flex align-items-center justify-content-between ms-3"
            >
              <div>
                <p class="fw-bold">*************</p>
                <p class="sub-text" style="margin-top: -6px">
                  You can change your password
                </p>
                <p class="text-success sub-text">Required</p>
              </div>

              <a href="{{url_for('dashboard.profile')}}" class="btn btn-primary mt-2 border-0 mt-xsm-0"
                >Manage</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">Identity verification</h4>
      </div>
      <div class="card-body">
        <div class="d-flex align-items-xsm-center">
          <div
            class="op-primary rounded-3 cw-60 d-flex align-items-center justify-content-center ch-60 mt-1 mt-xsm-0"
          >
            <img
              class="svg svgh-30 text-primary fill-primary replaced-svg"
              src="{{url_for('static', filename="dashboard/assets/icons/nid.svg")}}"
              alt=""
            />
          </div>
          <div class="w-100">
            <div
              class="d-xsm-flex align-items-center justify-content-between ms-3"
            >
              <div>
                <p class="fw-bold">xxx xxxxx xxx40</p>
                <p class="sub-text">Social Security Number</p>
                <p class="text-success sub-text">Verified</p>
              </div>

              <a href="{{url_for('dashboard.profile')}}" class="btn btn-primary mt-2 border-0 mt-xsm-0"
                >Manage</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title">
          Use 2-step verification to secure your transactions
        </h4>
      </div>
      <div class="card-body">
        <div class="d-flex align-items-center">
          <label class="switch checked-bg-success me-1">
            <input type="checkbox" checked="" id="secure" />
            <span class="slider round"> </span>
          </label>
          <label for="secure" class="c-pointer"
            >Any amount of cryptocurrency
            <b class="text-success">Most secure </b></label
          >
        </div>
        <div class="d-flex align-items-center">
          <label class="switch checked-bg-primary me-1">
            <input type="checkbox" checked="" id="day" />
            <span class="slider round"> </span>
          </label>
          <label for="day" class="c-pointer">Over 1.2000 BTC per day</label>
        </div>
        <div class="d-flex align-items-center">
          <label class="switch checked-bg-danger me-1">
            <input type="checkbox" checked="" id="never" />
            <span class="slider round"> </span>
          </label>
          <label for="never" class="c-pointer"
            >Never <b class="text-danger">Least secure</b></label
          >
        </div>
      </div>
    </div>
  </div>
</div>

</div>
        </div>
      </div>
    </main>

{% endblock %}

app/templates/dashboard/signin.html
{% extends 'dashboard/base.html' %}

{% block title %}Sign in{% endblock %}
{% block main %}
<!-- flashed message from server -->
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="container">
  <div class="row">
    {% for category, message in messages %}
      <div class="col-sm-6 col-md-6">
          <div class="alert alert-{{category}}">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                  ×</button>
             <span class="glyphicon glyphicon-info-sign"></span> <strong></strong>
              <hr class="message-inner-separator">
              <p>{{message}}</p>
          </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endif %}
{% endwith %}
<style>
hr.message-inner-separator
{
clear: both;
margin-top: 10px;
margin-bottom: 13px;
border: 0;
height: 1px;
background-image: -webkit-linear-gradient(left,rgba(0, 0, 0, 0),rgba(0, 0, 0, 0.15),rgba(0, 0, 0, 0));
background-image: -moz-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
background-image: -ms-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
background-image: -o-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));
}
</style>
<!-- endflash -->
<main>
  <div class="container">
<div class="row justify-content-center auth">
<div class="col-xl-5 col-lg-6 col-md-8 col-sm-10">
<div class="card p-0">
  <div class="card-body p-0">
    <form name="form" id="form" role="form" method="post" class="p-4">
      <div class="text-center mb-4">
        <div
          class="op-primary p-3 ch-75 cw-75 d-flex align-items-center justify-content-center m-auto rounded-circle"
        >
          <img
            src={{url_for('static', filename="dashboard/assets/icons/logout.svg")}}
            class="svg svgh-35 ms-2 fill-primary"
            alt=""
          />
        </div>
        <h4>Login your account</h4>
        <p class="text-muted">
          Enter your credentials to access your account
        </p>
      </div>
      <div class="row g-3">
        <div class="col-12">
          <div class="input-group p-2">
            <span class="input-group-text p-2 bg-transparent">
              <img
                src={{url_for('static', filename="dashboard/assets/icons/envelope.svg")}}
                class="svg svgh-15 cw-20"
                alt=""
              />
            </span>
            <input
              type="email"
              name="email"
              class="form-control"
              placeholder="example@example.com"
              required
            />
          </div>
        </div>
        <div class="col-12">
          <div class="input-group p-2">
            <span class="input-group-text p-2 bg-transparent">
              <img
                src={{url_for('static', filename="dashboard/assets/icons/lock.svg")}}
                class="svg svgh-20 cw-20"
                alt=""
              />
            </span>
            <input
              type="password"
              name="password"
              class="form-control"
              placeholder="Password"
              required
            />
          </div>
        </div>
        <div class="col-6">
          <div class="d-flex align-items-center">
            <label class="switch checked-bg-primary me-1">
              <input type="checkbox" name="remember" checked="" id="never" />
              <span class="slider round"> </span>
            </label>
            <label for="never" class="c-pointer text-muted"
              >Remember me</label
            >
          </div>
        </div>
        <div class="col-6">
          <a href={{url_for('dashboard.reset_password')}} class="text-end text-primary d-block"
            >Forgot Password?</a
          >
        </div>
        <div class="col-12">
          <input
            type="submit"
            value="Log In"
            class="btn btn-primary p-2 cfs-18 fw-500 border-0 d-block w-100 rounded-0"
          />
        </div>
      </div>
    </form>
    <div class="text-center border-top p-3">
      <p>
        Don't have an account?
        <a href={{url_for('frontend.register')}} class="text-primary">Sign up</a>
      </p>
    </div>
  </div>
</div>
</div>
</div>

</div>
</main>
{% endblock %}