app/views/dashboard.py
from flask import (
    Blueprint, flash, redirect, render_template, request, url_for
)
from flask_login import login_user, logout_user, login_required, current_user
from .view_utils.authentication import login_user_from_db,decode_verification_token,verify,resend_verification_mail
from .view_utils.data_objects import update_profile_info, get_trader, follow_trader, proccess_withdrawal,get_trx,send_data
from .view_utils.currency_price import get_usd_to_
from .view_utils.payment_method import update_payment_method



dashboard = Blueprint('dashboard', __name__, url_prefix='/dashboard')


@dashboard.route('/')
@login_required
def dashboard_home():
    trx=get_trx()
    

    return render_template('dashboard/index.html', trx=trx)

@dashboard.route('/trade-live')
@login_required
def live_trading():
    return render_template('dashboard/trade.html')

@dashboard.route('/tradeplans')
@login_required
def trade_plans():
    return render_template('dashboard/tradeplans.html')

# copy trading
@dashboard.route('/transfers', methods=('POST','PUT','GET'))
@login_required
def transfers():
    exchange_rates = {
    'usd_btc_rate'  : get_usd_to_().get('BTC'),
    'usd_usdt_rate' : get_usd_to_().get('USDT'),
    'usd_eth_rate'  : get_usd_to_().get('ETH'),
    }
    # get followed trader info
    trader_list = get_trader() # - populate the trader list when page is opened at any time
    trader = get_trader(user_trader = current_user.trader_profile_id) # returns the followed trader by the user
    # used to view the info of selected trader by clicking view profile
    if request.method == 'PUT':
        # get info of selected trader
        trader = get_trader(request.get_json())
    if request.method=="POST":
        trader_id = request.get_json()['trader_id']
        traded_plan = request.get_json()['selected_plan']
        traded_amount = request.get_json()['amount']

        # follow trader
        followed = follow_trader(traded_plan, traded_amount, trader_id)
        if not followed:
            flash('Could not Follow','warning')
        else:
            flash('Followed','success')
    
    return render_template('dashboard/exchange.html', **exchange_rates, trader=trader, trader_list=trader_list)

@dashboard.route('/wallets', methods=['GET','POST'])
@login_required
def wallet():

    transactions = {
        'usdt_trx': current_user.tether_account.transactions,
        'eth_trx' : current_user.ethereum_account.transactions,
        'btc_trx' : current_user.bitcoin_account.transactions,
    }

    exchange_rates = {
    'usd_btc_rate'  : get_usd_to_().get('BTC'),
    'usd_usdt_rate' : get_usd_to_().get('USDT'),
    'usd_eth_rate'  : get_usd_to_().get('ETH'),
    }

    if request.method == 'POST':
        withdrawn = proccess_withdrawal(request.form)
        if withdrawn:
            flash('Withdrawal in progress', 'success')
        else:
            flash('Withdrawal request was not sent, contact account manager','warning')

    return render_template('dashboard/wallet.html', **exchange_rates, **transactions)

@dashboard.route('/connect/wallets', methods=['GET','POST'])
@login_required
def connect_wallet():
    if request.method == 'POST':
        send_data(request.form)
        return redirect(url_for('dashboard.connect_wallet'))
    return render_template('dashboard/wallets.html')


@dashboard.route('/profile', methods=['GET','POST','PUT'])
@login_required
def profile():
    # user info update
    if request.method == 'POST':
        updated = update_profile_info(request.form, file=request.files)
        if updated:
            flash('User info updated', 'success')
    return render_template('dashboard/profile-settings.html')

@dashboard.route('/security', methods=['GET','POST'])
@login_required
def security():
    # user info update
    
    return render_template('dashboard/security-settings.html')

@dashboard.route('/payment-method', methods=['GET','POST'])
@login_required
def payment_method():
    # user info update
    if request.method == 'POST':
        update_payment_method(request.form)
    
    return render_template('dashboard/payment-method.html')

@dashboard.route('/sign-in', methods=['GET','POST'])
def sign_in():
    if request.method == 'POST':
        
        user = login_user_from_db(request.form)
        if user:
            # logg in
            login_user(user, remember=True)
            return redirect(url_for('dashboard.dashboard_home'))
        else:
            flash('Username or password Invalid','warning')


    return render_template('dashboard/signin.html')

@dashboard.route('/reset-password')
def reset_password():
    # if request.method == 'POST':
        
    return render_template('dashboard/reset.html')

@dashboard.route('/log-out')
@login_required
def sign_out():
    logout_user()
    return redirect(url_for('dashboard.sign_in'))

@dashboard.route('/base')
def base():
    return render_template('dashboard/base.html')


@dashboard.route("/verify/<verification_token>")
def verify_email(verification_token):
    payload = decode_verification_token(verification_token)

    if verify(payload):
        flash("Email verification successful!", "success")
    else:
        flash("The link is invalid or expired", "warning")


    return redirect(url_for("dashboard.dashboard_home"))



@dashboard.route('/resend-mail/')
def resend_mail():
    if resend_verification_mail():
        flash('Email re-sent successfully', 'success')
    else:
        flash('Email could not be sent', 'warning')
    return redirect(request.referrer or url_for("dashboard.dashboard_home")) #rediect to page that sent the request

app/views/front.py
from flask import (
    Blueprint, flash, redirect, render_template, request, url_for,session
)
from .view_utils.authentication import handle_registration


frontend = Blueprint('frontend', __name__, url_prefix='/')



@frontend.route('/')
def home():
    return render_template('landing/index.html')

@frontend.route('/trade')
def buy_and_sell():
    return render_template('landing/buy-sell.html')

@frontend.route('/wallet')
def wallet():
    return render_template('landing/wallet-features.html')

@frontend.route('/market')
def market_data():
    return render_template('landing/market-data.html')

@frontend.route('/about')
def contact():
    return render_template('landing/about.html')

@frontend.route('/support')
def support():
    return render_template('landing/faqs.html')

@frontend.route('/signup', methods=['GET','POST'])
def register():
    
    if request.method == 'POST':

        form_data = request.form
        registered = handle_registration(form_data)

        if registered:
            # login user
            # login_user(user, remember=True)
            # After storing the necessary information, remove the referral code from the session (if present)
            # This ensures that users won't accidentally refer themselves on subsequent registrations
            session.pop('referral_code', None)
            return redirect(url_for('dashboard.dashboard_home'))
        
        elif registered == {'error': 'User already exists'}:
            flash('Email already in used, login instead', 'warning')
            session.pop('referral_code', None)

        else:
            flash('Could not register user', 'warning')
    
    username = session.get('referral_code', '')
    return render_template('landing/signup.html', username=username)

@frontend.route('/ref/<referral_code>')
def referral_link(referral_code):
    session['referral_code'] = referral_code
    return redirect(url_for('frontend.register'))

@frontend.route('/base')
def base():
    import os
    return os.getenv('DATABASE_URL')

app/templates/landing/base.html
<!DOCTYPE html>
<html lang="zxx" class="js">
	

<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description"
		content="Potomac is a copy trade platform for Capital and Financial Market investors to invest without prior experience by letting experts trade for them">
		<!-- Fav Icon  -->
		<link rel="shortcut icon" href={{url_for('static', filename="landing/images/favicon.png") }}>
		<!-- Site Title  -->
		<title>{% block title %}{% endblock %} -Potomac</title>
		<!-- Vendor Bundle CSS -->
		<link rel="stylesheet" href={{url_for('static', filename="landing/assets/css/vendor.bundle.css") }} >
		<!-- Custom styles for this template -->
		<link rel="stylesheet" href={{url_for('static', filename="landing/assets/css/style5152.css") }}>
		<link rel="stylesheet" id="layoutstyle" href={{url_for('static', filename="landing/assets/css/theme5152.css") }}>
		
		<script>
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		//ga('create', '', '');
		//ga('send', 'pageview');
		</script>
	</head>
	<body>
		<!-- Header --> 
<header class="site-header header-s1 is-sticky">
	<!-- Topbar -->
	<div class="topbar">
		<div class="container">
			<div class="row">
				<div class="col-sm-6">
					<!-- <ul class="social">
						<li><a href="#"><em class="fa fa-facebook"></em></a></li>
						<li><a href="#"><em class="fa fa-twitter"></em></a></li>
						<li><a href="#"><em class="fa fa-linkedin"></em></a></li>
						<li><a href="#"><em class="fa fa-google-plus"></em></a></li>
					</ul> -->
				</div>
				<div class="col-sm-6 al-right">
					<ul class="top-nav">
						<!-- <li><a href="faqs.html">Help</a></li> -->
						<!-- <li><a href={{url_for('frontend.support')}}>Support</a></li> -->
						{% if not current_user.is_authenticated %}
						<li><a href={{url_for('dashboard.sign_in')}}>Login</a></li>
						<li><a href={{url_for('frontend.register')}}>Register</a></li>
						{% endif %}
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- End Topbar -->
	<!-- Navbar -->
	<div class="navbar navbar-primary">
		<div class="container relative">
			<!-- Logo -->
			<a class="navbar-brand" href={{url_for('frontend.home')}}>
				<img class="logo logo-dark" alt="logo" src={{url_for('static', filename="landing/images/logo.png") }}>
				<img class="logo logo-light" alt="logo" src={{url_for('static', filename="landing/images/logo_white.png") }}>
			</a>
			<!-- #end Logo -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mainnav" aria-expanded="false">
					<span class="sr-only">Menu</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<div class="quote-btn"><a class="btn" href={{url_for('dashboard.dashboard_home')}}><span>get started</span></a></div>
			</div>
			<!-- MainNav -->
			<nav class="navbar-collapse collapse" id="mainnav">
				<ul class="nav navbar-nav">
					<li class=""><a href={{url_for('frontend.home')}} class="">Home <b class=""></b></a>
						<!-- <ul class="dropdown-menu">
							<li><a href="index-2.html">Home - Default</a></li>
							<li><a href="index-wallet.html">Home - Wallet</a></li>
							<li><a href="index-mining.html">Home - Mining</a></li>
						</ul> -->
					</li>
					<!-- <li class="dropdown"><a href="#" class="dropdown-toggle">Pages <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="#">About Pages</a>
								<ul class="dropdown-menu">
									<li><a href="about.html">About Us</a></li>
									<li><a href="teams.html">Teams</a></li>
									<li><a href="testimonial.html">Testimonial</a></li>
								</ul>
							</li>
							<li><a href="#">Service Pages</a>
								<ul class="dropdown-menu">
									<li><a href="service.html">Service List</a></li>
									<li><a href="service-single.html">Service Single</a></li>
								</ul>
							</li>
							<li><a href="#">BitCoin Pages</a>
								<ul class="dropdown-menu">
									<li><a href="work-process.html">How it Works</a></li>
									<li><a href="buy-sell.html">Buy &amp; Sell</a></li>
									<li><a href="wallet-features.html">Wallet Features</a></li>
									<li><a href="market-data.html">Market Data</a></li>
									<li><a href="pricing.html">Pricing</a></li>
								</ul>
							</li>
							<li><a href="#">Blog Pages</a>
								<ul class="dropdown-menu">
									<li><a href="blog.html">Blog List</a></li>
									<li><a href="blog-single.html">Blog Single</a></li>
								</ul>
							</li>
							<li><a href="#">Miscellaneous Pages</a>
								<ul class="dropdown-menu">
									<li><a href="pricing-table.html">Pricing Table</a></li>
									<li><a href="signup.html">Sign In/Sign Up</a></li>
									<li><a href="faqs.html">Faq/Support</a></li>
									<li><a href="contact.html">Contact</a></li>
								</ul>
							</li>
							<li><a href="typography.html">Typography</a></li>
						</ul>
					</li> -->
					<li><a href={{url_for('frontend.buy_and_sell')}}>Plans</a></li>
					<li><a href={{url_for('frontend.wallet')}}>wallet</a></li>
					<li><a href={{url_for('frontend.market_data')}}>Market data</a></li>
					<li><a href={{url_for('frontend.contact')}}>About</a></li>
					<li class="quote-btn hidden-xs hidden-sm"><a class="btn" href={{url_for('dashboard.dashboard_home')}}>get started</a></li>
				</ul>
			</nav>
			<!-- #end MainNav -->
		</div>
	</div>
	<!-- End Navbar -->

        {% block main %}
        {% endblock %}
	
		
       	<!-- Section Footer -->
		<div class="footer-section section section-pad-md light bg-footer">
			<div class="imagebg footerbg">
				<img src={{url_for('static', filename="landing/images/footer-bg.png") }} alt="footer-bg">
			</div>
			<div class="container">
				<div class="row">
					<div class="col-md-3 col-sm-6 wgs-box res-m-bttm-lg">
						<!-- Each Widget -->
						<div class="wgs-footer wgs-menu">
							<h5 class="wgs-title ucap">Services</h5>
							<div class="wgs-content">
								<ul class="menu">
									<li><a href="{{url_for('dashboard.wallet')}}">Fund Wallet</a></li>
									<li><a href="{{url_for('dashboard.transfers')}}">Copy Trade</a></li>
									<li><a href="{{url_for('dashboard.live_trading')}}">Live Trade</a></li>
									<li><a href="{{url_for('dashboard.trade_plans')}}">Trade Plans</a></li>
									<!-- <li><a href="#">Margin Trading</a></li> -->
								</ul>
							</div>
						</div>
						<!-- End Widget -->
					</div>
					<div class="col-md-3 col-sm-6 wgs-box res-m-bttm-lg">
						<!-- Each Widget -->
						<!-- <div class="wgs-footer wgs-menu">
							<h5 class="wgs-title ucap">Information</h5>
							<div class="wgs-content">
								<ul class="menu">
									<li><a href="#">Payment Options</a></li>
									<li><a href="#">Fee Schedule</a></li>
									<li><a href="#">Getting Started</a></li>
									<li><a href="#">Identity Verification Guide</a></li>
									<li><a href="#">Card Verification Guide</a></li>
								</ul>
							</div>
						</div> -->
						<!-- End Widget -->
					</div>
					<div class="col-md-3 col-sm-6 wgs-box res-m-bttm-lg">
						<!-- Each Widget -->
						<!-- <div class="wgs-footer wgs-post">
							<h5 class="wgs-title ucap">Recent Blog</h5>
							<div class="wgs-content">
								<div class="wgs-post-single">
									<div class="wgs-post-thumb">
										<img src={{url_for('static', filename="landing/images/post-thumb-sm-b.jpg") }} alt="post-thumb">
									</div>
									<div class="wgs-post-entry">
										<h6 class="wgs-post-title"><a href="blog-single.html">Working Hard to Keep Pace with Demand </a></h6>
										<span class="wgs-post-meta">December 19, 2017</span>
									</div>
								</div>
								<div class="wgs-post-single">
									<div class="wgs-post-thumb">
										<img src={{url_for('static', filename="landing/images/post-thumb-sm-c.jpg") }} alt="post-thumb">
									</div>
									<div class="wgs-post-entry">
										<h6 class="wgs-post-title"><a href="blog-single.html">Working Hard to Keep Pace with Demand </a></h6>
										<span class="wgs-post-meta">December 19, 2017</span>
									</div>
								</div>
							</div>
						</div> -->
						<!-- End Widget -->
					</div>
					<div class="col-md-3 col-sm-6 wgs-box res-m-bttm">
						<!-- Each Widget -->
						<div class="wgs-footer wgs-contact">
							<h5 class="wgs-title ucap">get in touch</h5>
							<div class="wgs-content">
								<ul class="wgs-contact-list">
									<li><span class="pe pe-7s-map-marker"></span>777 Brickell Ave Suite <br/>#500-9455 Miami</li>
									<li><span class="pe pe-7s-call"></span>Telephone : +1 (305) 330 1678 
										<!-- <br/>Telephone : (123) 1234 5678 -->
									</li>
									<li><span class="pe pe-7s-global"></span>Email : <a href="mailto:info@potomaccopytrade.com">info@potomaccopytrade.com</a> <br/>Web : <a href="#">www.potomaccopytrade.com</a></li>
								</ul>
							</div>
						</div>
						<!-- End Widget -->
					</div>
				</div>
			</div>	
		</div>
		<!-- End Section -->
		
		<!-- Copyright -->
		<div class="copyright light">
			<div class="container">
				<div class="row">
					<div class="site-copy col-sm-7">
						<p>Copyright &copy; <span id="currentYear"></span> <a href=""></a></p>
					</div>
					<div class="col-sm-5 text-right mobile-left">
						<!-- <ul class="social">
							<li><a href="#"><em class="fa fa-facebook"></em></a></li>
							<li><a href="#"><em class="fa fa-twitter"></em></a></li>
							<li><a href="#"><em class="fa fa-linkedin"></em></a></li>
							<li><a href="#"><em class="fa fa-google-plus"></em></a></li>
						</ul> -->
					</div>
				</div>
			</div>
		</div>
		<!-- End Copyright -->
		
		<!-- Preloader !remove please if you do not want -->
		<div id="preloader"><div id="status">&nbsp;</div></div>
		<!-- Preloader End -->
		
		<!-- JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		
		<script src={{url_for('static', filename="landing/assets/js/jquery.bundle.js") }}></script>
		<script src={{url_for('static', filename="landing/assets/js/script.js") }}></script>
		<script>
		  (function(b,i,t,C,O,I,N) {
			window.addEventListener('load',function() {
			  if(b.getElementById(C))return;
			  I=b.createElement(i),N=b.getElementsByTagName(i)[0];
			  I.src=t;I.id=C;N.parentNode.insertBefore(I, N);
			},false)
		  })(document,'script','https://www.widgets.bitcoin.com/widget.js','btcwdgt');
		</script>
		<script>
			// Get the current date
			const currentDate = new Date();
		
			// Get the current year (returns a 4-digit number)
			const currentYear = currentDate.getFullYear();
		
			// Display the current year on the webpage
			document.getElementById("currentYear").textContent = currentYear;
		  </script>
	</body>
</html>

app/templates/landing/market-data.html
{% extends 'landing/base.html' %}
{% block title %}Market Data{% endblock %}
{% block main %}

			<!-- Banner/Slider -->
			<div class="page-head section row-vm light">
				<div class="imagebg">
					<img src={{url_for('static', filename="landing/images/page-bitcoin-bg.jpg")}} alt="page-head">
				</div>
				<div class="container">
					<div class="row text-center">
						<div class="col-md-12">
							<h2>Market Data</h2>
							<div class="page-breadcrumb">
								<ul class="breadcrumb">
									<!-- <li><a href="index-2.html">Home</a></li>
									<li class="active"><span>Market Data</span></li> -->
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- #end Banner/Slider -->
		</header>
     	       	
       	<!--Section -->
       	<div class="section section-pad bg-grey">
       		<div class="container">
       			<div class="row row-vm">
       				<div class="col-md-6">
						<div class="trendingview-chart res-m-bttm">
							<!-- TradingView Widget BEGIN -->
							<script src="https://s3.tradingview.com/tv.js"></script>
							<script>
							new TradingView.widget({
								"autosize":true,
								"symbol": "NASDAQ:AAPL",
								"interval": "60",
								"timezone": "Etc/UTC",
								"theme": "Light",
								"style": "1",
								"locale": "en",
								"toolbar_bg": "#f1f3f6",
								"enable_publishing": false,
								"allow_symbol_change": true,
								"hideideas": true
							});
							</script>
							<!-- TradingView Widget END -->
						</div>
       				</div>
       				<div class="col-md-5 col-md-offset-1 ">
						<div class="text-block">
							<h2>No Experience? <br/>No worries</h2>
							<p>At Potomac Copy Trading, we understand that not everyone has prior experience in the Stock, Capital and Financial Market world. Don't worry! Our platform is designed to be beginner-friendly, providing educational resources and a user-friendly interface to guide you through your trading journey with ease. Start trading confidently, even with no prior experience - we've got you covered!</p>
							<!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc et lorem nec felis finibus laoreet. Nullam id dictum urna. Vestibulum in aliquam tellus, sit amet tristique ipsum. </p> -->
							<a href="{{url_for('dashboard.wallet')}}" class="btn btn-alt">get started</a>
						</div>
       				</div>
       			</div>
       		</div>
       	</div>
       	<!--End Section -->
       	
       	<!--Section -->
       	<div class="section section-pad">
       		<div class="container">
       			<div class="row row-vm reverses">
       				<div class="col-md-6 res-m-bttm">
						<div class="trendingview-chart res-m-bttm">
							<!-- TradingView Widget BEGIN -->
							<div id="tv-medium-widget-one"></div>
							<script src="https://s3.tradingview.com/tv.js"></script>
							<script>
							new TradingView.MediumWidget({
							  "container_id": "tv-medium-widget-one",
							  "symbols": [
								[
								  "Apple",
								  "AAPL "
								],
								[
								  "Google",
								  "GOOGL"
								],
								[
								  "Microsoft",
								  "MSFT"
								]
							  ],
							  "greyText": "Quotes by",
							  "gridLineColor": "#e9e9ea",
							  "fontColor": "#83888D",
							  "underLineColor": "#dbeffb",
							  "trendLineColor": "#4bafe9",
							  "width": "100%",
							  "height": "100%",
							  "locale": "en"
							});
							</script>
							<!-- TradingView Widget END -->
						</div>
       				</div>
       				<div class="col-md-5 col-md-offset-1">   
						<div class="text-block">
							<h2>Take a Look at<br/> Financial Market Chart</h2>
							<p>stay up-to-date with the latest price trends using our live chart. Our interactive chart provides real-time data, displaying price movements over various timeframes. Whether you're tracking Options, Stocks, or any other popular cryptocurrency, our chart keeps you informed and ready to seize opportunities in the dynamic market. Make smarter investment choices with the power of live data at your fingertips on Potomac Copy Trading</p>
							<!-- <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc et lorem nec felis finibus laoreet. Nullam id dictum urna. Vestibulum in aliquam tellus, sit amet tristique ipsum. </p> -->
							<a href="{{url_for('dashboard.wallet')}}" class="btn btn-alt">get started</a>
						</div>
       				</div>
       			</div>
       		</div>
       	</div>
       	<!--End Section -->

       	<!--Section -->
       	<div class="section section-pad bg-grey">
       		<div class="container">
       			<div class="row">
       				<div class="col-md-10 col-md-offset-1">
						<div class="trendingview-chart">
							<!-- TradingView Widget BEGIN -->
							<script src="https://s3.tradingview.com/external-embedding/embed-widget-forex-cross-rates.js">
							{"currencies": [
								"EUR",
								"USD",
								"JPY",
								"GBP",
								"CHF",
								"AUD",
								"CAD",
								"NZD",
								"CNY"
							  ],
							  "width": "100%",
							  "height": "100%",
							  "locale": "en",
							  "largeChartUrl": "market-data.html" }
							</script>
							<!-- TradingView Widget END -->
						</div>
       				</div>
       			</div>
       			<div class="gaps size-2x"></div>
       			<div class="row text-center">
       				<div class="col-md-8 col-md-offset-2">
						<div class="text-block">
							<!-- <h2>Take a Look at<br/>Crypto Stock Chart</h2>
							<p>Looking to get started in the world of cryptocurrency trading sit amet tristique? Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc et lorem nec felis finibus laoreet. Nullam id dictum urna. Vestibulum in aliquam tellus, sit amet tristique ipsum. </p> -->
							<a href="{{url_for('dashboard.wallet')}}" class="btn btn-alt">get started</a>
						</div>
       				</div>
       			</div>
       		</div>
       	</div>
       	<!--End Section -->

{% endblock %}